# Generated by Django 5.2.13 on 2026-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('raw_comments', models.JSONField()),
                ('clean_comments', models.JSONField()),
                ('augmented_comments', models.JSONField()),
                ('iqr_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
